### PR TITLE
Setup project 

### PR DESCRIPTION
**Pull request by dev-mamun**
In this PR, I

- Set up the environment and tools needed to develop a React application.
- Set up and install the linter.
- The application is running in the browser without errors.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @dev-mamun, Kindly add the key features and future features sections to your readme

**Comment by dev-mamun** [comment]
> Hi @dev-mamun, Kindly add the key features and future features sections to your readme

What will be the key features & future features will be for this? current PR @prolajumokeoni

**Comment by prolajumokeoni** [comment]
> > Hi @dev-mamun, Kindly add the key features and future features sections to your readme
> 
> What will be the key features & future features will be for this? current PR
> @dev-mamun, Kindly go through the learning materials and deduct the main features of your project you can also check the [project big picture ](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_setup.md#need-a-big-picture) to coin future features for your app 👍🏿

**Comment by prolajumokeoni** [comment]
Hi @dev-mamun 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the key features & future features section in your readme

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Mamun,  

Your project is complete! 🏁 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉💯🌟 

## Highlights 🎯 
💠  Bootstrapped react project correctly!
💠  ReadMe looks great!

Cheers..Happy coding! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
